Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/ParenthesesAroundCondition:
  AllowInMultilineConditions: true

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - Rakefile
